name: Client CI

on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/client-ci.yml'
  pull_request:
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint (skip if none)
        run: |
          npm run lint || echo "No lint script"

      - name: Build
        env:
          VITE_API_URL: http://localhost:5000
          VITE_FIREBASE_API_KEY: dummy
          VITE_FIREBASE_AUTH_DOMAIN: dummy
          VITE_FIREBASE_PROJECT_ID: dummy
          VITE_FIREBASE_STORAGE_BUCKET: dummy
          VITE_FIREBASE_MESSAGING_SENDER_ID: dummy
          VITE_FIREBASE_APP_ID: dummy
          VITE_FIREBASE_MEASUREMENT_ID: dummy
        run: npm run build

