name: Deploy (Render + Vercel)

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    if: ${{ secrets.RENDER_DEPLOY_HOOK_URL != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy hook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

  deploy-frontend:
    if: ${{ secrets.VERCEL_DEPLOY_HOOK_URL != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel deploy hook
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"

